# Generated by Django 5.2.15 on 2026-06-16 13:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام پلن')),
                ('code', models.SlugField(choices=[('free', 'رایگان'), ('silver', 'نقره\u200cای'), ('gold', 'طلایی'), ('enterprise', 'سازمانی')], max_length=32, unique=True, verbose_name='کد پلن')),
                ('monthly_price', models.PositiveIntegerField(default=0, verbose_name='قیمت ماهانه به تومان')),
                ('yearly_price', models.PositiveIntegerField(default=0, verbose_name='قیمت سالانه به تومان')),
                ('max_services', models.PositiveIntegerField(default=3, verbose_name='حداکثر خدمات')),
                ('max_bookings_per_month', models.PositiveIntegerField(default=30, verbose_name='حداکثر رزرو ماهانه')),
                ('max_staff', models.PositiveIntegerField(default=1, verbose_name='حداکثر کارمند')),
                ('sms_credit', models.PositiveIntegerField(default=0, verbose_name='اعتبار پیامک ماهانه')),
                ('online_payment', models.BooleanField(default=False, verbose_name='پرداخت آنلاین')),
                ('deposit_payment', models.BooleanField(default=False, verbose_name='بیعانه')),
                ('remove_branding', models.BooleanField(default=False, verbose_name='حذف برندینگ')),
                ('custom_domain', models.BooleanField(default=False, verbose_name='دامنه اختصاصی')),
                ('advanced_reports', models.BooleanField(default=False, verbose_name='گزارش پیشرفته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='پلن پیشنهادی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('description', models.CharField(blank=True, max_length=220, verbose_name='توضیح کوتاه')),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'پلن\u200cهای اشتراک',
                'ordering': ['order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان قابلیت')),
                ('is_available', models.BooleanField(default=True, verbose_name='فعال برای این پلن')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='plans.subscriptionplan', verbose_name='پلن')),
            ],
            options={
                'verbose_name': 'قابلیت پلن',
                'verbose_name_plural': 'قابلیت\u200cهای پلن\u200cها',
                'ordering': ['plan', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='شروع')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='تمدید خودکار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.subscriptionplan', verbose_name='پلن')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اشتراک کاربر',
                'verbose_name_plural': 'اشتراک\u200cهای کاربران',
            },
        ),
    ]
