# Generated by Django 5.2.15 on 2026-06-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=220, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'سوال پرتکرار',
                'verbose_name_plural': 'سوالات پرتکرار',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=32, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_checked', models.BooleanField(default=False, verbose_name='بررسی شده')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='نوبتک', max_length=80, verbose_name='نام سایت')),
                ('tagline', models.CharField(default='لینک رزرو آنلاین برای هر کسب\u200cوکار', max_length=180, verbose_name='شعار')),
                ('hero_title', models.CharField(default='برای کسب\u200cوکارت صفحه رزرو آنلاین بساز', max_length=220, verbose_name='تیتر اصلی')),
                ('hero_subtitle', models.TextField(default='مشتری\u200cها ۲۴ ساعته وقت، خدمت، کلاس یا مکان رزرو می\u200cکنند و تو همه چیز را از یک پنل حرفه\u200cای مدیریت می\u200cکنی.', verbose_name='زیرتیتر اصلی')),
                ('contact_phone', models.CharField(blank=True, max_length=32, verbose_name='شماره تماس')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل تماس')),
                ('instagram_url', models.URLField(blank=True, verbose_name='لینک اینستاگرام')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='لینک واتساپ')),
                ('address', models.CharField(blank=True, max_length=260, verbose_name='آدرس')),
                ('meta_description', models.CharField(default='نوبتک پلتفرم ساخت صفحه رزرو آنلاین برای کسب\u200cوکارها، مشاوران، کلاس\u200cها، سالن\u200cها و مکان\u200cهای قابل رزرو است.', max_length=260, verbose_name='متا دیسکریپشن')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام')),
                ('role', models.CharField(blank=True, max_length=160, verbose_name='سمت / کسب\u200cوکار')),
                ('quote', models.TextField(verbose_name='متن نظر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'نظر مشتری',
                'verbose_name_plural': 'نظرات مشتریان',
                'ordering': ['order', 'id'],
            },
        ),
    ]
