# Generated by Django 5.2.15 on 2026-06-16 13:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('description', models.CharField(blank=True, max_length=220, verbose_name='توضیح')),
                ('icon', models.CharField(default='calendar-check', max_length=40, verbose_name='آیکن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی کسب\u200cوکار',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای کسب\u200cوکار',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='نام کسب\u200cوکار')),
                ('slug', models.SlugField(allow_unicode=True, max_length=160, unique=True, verbose_name='لینک اختصاصی')),
                ('short_description', models.CharField(blank=True, max_length=240, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='معرفی کامل')),
                ('business_type', models.CharField(choices=[('in_person', 'حضوری'), ('online', 'آنلاین'), ('both', 'حضوری و آنلاین')], default='both', max_length=20, verbose_name='نوع فعالیت')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='شهر')),
                ('address', models.CharField(blank=True, max_length=260, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='شماره تماس')),
                ('instagram_url', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='واتساپ')),
                ('website_url', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business/logos/', verbose_name='لوگو')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='business/covers/', verbose_name='کاور')),
                ('booking_policy', models.TextField(default='لطفاً در زمان انتخاب\u200cشده حضور داشته باشید. امکان لغو رزرو طبق قوانین کسب\u200cوکار انجام می\u200cشود.', verbose_name='قوانین رزرو')),
                ('cancellation_hours', models.PositiveIntegerField(default=24, verbose_name='امکان لغو تا چند ساعت قبل')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='businesses.businesscategory', verbose_name='دسته\u200cبندی')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'پروفایل کسب\u200cوکار',
                'verbose_name_plural': 'پروفایل\u200cهای کسب\u200cوکار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام کارمند')),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='سمت')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='شماره تماس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='businesses.businessprofile', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='نام خدمت')),
                ('description', models.TextField(blank=True, verbose_name='توضیح خدمت')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت به تومان')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='مدت\u200cزمان به دقیقه')),
                ('buffer_minutes', models.PositiveIntegerField(default=0, verbose_name='فاصله بعد از رزرو')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='ظرفیت هر بازه')),
                ('payment_mode', models.CharField(choices=[('none', 'بدون پرداخت'), ('full', 'پرداخت کامل'), ('fixed_deposit', 'بیعانه ثابت'), ('percent_deposit', 'بیعانه درصدی')], default='none', max_length=24, verbose_name='نوع پرداخت')),
                ('deposit_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ بیعانه ثابت')),
                ('deposit_percent', models.PositiveIntegerField(default=0, verbose_name='درصد بیعانه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='businesses.businessprofile', verbose_name='کسب\u200cوکار')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='businesses.staffmember', verbose_name='ارائه\u200cدهنده')),
            ],
            options={
                'verbose_name': 'خدمت قابل رزرو',
                'verbose_name_plural': 'خدمات قابل رزرو',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='زمان بسته', max_length=120, verbose_name='عنوان')),
                ('starts_at', models.DateTimeField(verbose_name='شروع')),
                ('ends_at', models.DateTimeField(verbose_name='پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='businesses.businessprofile', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'بستن زمان',
                'verbose_name_plural': 'زمان\u200cهای بسته شده',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(5, 'شنبه'), (6, 'یکشنبه'), (0, 'دوشنبه'), (1, 'سه\u200cشنبه'), (2, 'چهارشنبه'), (3, 'پنجشنبه'), (4, 'جمعه')], verbose_name='روز هفته')),
                ('opens_at', models.TimeField(default=datetime.time(9, 0), verbose_name='شروع کار')),
                ('closes_at', models.TimeField(default=datetime.time(18, 0), verbose_name='پایان کار')),
                ('break_starts_at', models.TimeField(blank=True, null=True, verbose_name='شروع استراحت')),
                ('break_ends_at', models.TimeField(blank=True, null=True, verbose_name='پایان استراحت')),
                ('is_open', models.BooleanField(default=True, verbose_name='باز است')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='businesses.businessprofile', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'ساعت کاری',
                'verbose_name_plural': 'ساعت\u200cهای کاری',
                'ordering': ['weekday'],
                'unique_together': {('business', 'weekday')},
            },
        ),
    ]
