# Generated by Django 5.2.15 on 2026-06-16 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120, verbose_name='نام مشتری')),
                ('customer_phone', models.CharField(max_length=32, verbose_name='شماره موبایل')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('starts_at', models.DateTimeField(verbose_name='شروع رزرو')),
                ('ends_at', models.DateTimeField(verbose_name='پایان رزرو')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('awaiting_payment', 'در انتظار پرداخت'), ('confirmed', 'تأیید شده'), ('cancelled_by_customer', 'لغو شده توسط مشتری'), ('cancelled_by_business', 'لغو شده توسط کسب\u200cوکار'), ('done', 'انجام شده'), ('no_show', 'عدم حضور'), ('expired', 'منقضی شده')], default='pending', max_length=32, verbose_name='وضعیت')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت خدمت')),
                ('payable_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ قابل پرداخت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('tracking_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='کد پیگیری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='businesses.businessprofile', verbose_name='کسب\u200cوکار')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='businesses.service', verbose_name='خدمت')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='businesses.staffmember', verbose_name='ارائه\u200cدهنده')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ')),
                ('gateway', models.CharField(default='درگاه آزمایشی', max_length=80, verbose_name='درگاه')),
                ('authority', models.CharField(blank=True, max_length=120, verbose_name='شناسه پرداخت')),
                ('status', models.CharField(choices=[('init', 'ایجاد شده'), ('success', 'موفق'), ('failed', 'ناموفق'), ('refunded', 'برگشت داده شده')], default='init', max_length=16, verbose_name='وضعیت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking', verbose_name='رزرو')),
            ],
            options={
                'verbose_name': 'تراکنش پرداخت',
                'verbose_name_plural': 'تراکنش\u200cهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['business', 'starts_at'], name='bookings_bo_busines_97eb15_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service', 'starts_at'], name='bookings_bo_service_1a3201_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tracking_code'], name='bookings_bo_trackin_e2c3d7_idx'),
        ),
    ]
